import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} bg-gray-100 text-gray-900`}>
        {children}
      </body>
    </html>
  );
}
